# Generated by Django 3.1 on 2020-08-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('f', 'FAILED'), ('p', 'PASSED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.TextField(max_length=500)),
                ('title', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('no_of_questions', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('multiple_choice_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_choices.multiplechoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_statement', models.CharField(max_length=100, unique=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_choices.question')),
            ],
        ),
    ]
