# Generated by Django 3.1 on 2020-08-30 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_statement', models.CharField(max_length=100, unique=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('choices', models.ManyToManyField(related_name='choices', to='multiple_choices.Choice')),
                ('correct_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_choices.choice')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('duration', models.TimeField()),
                ('no_of_questions', models.IntegerField(default=10)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiple_choices.question')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentTaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('f', 'FAILED'), ('p', 'PASSED')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
