# Generated by Django 3.1 on 2020-09-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiple_choices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttaker',
            name='username',
        ),
        migrations.AddField(
            model_name='assessmenttaker',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmenttaker',
            name='status',
            field=models.CharField(choices=[('f', 'FAILED'), ('p', 'PASSED')], default=('f', 'FAILED'), max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_statement',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='passage',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_asked',
            field=models.CharField(max_length=200),
        ),
    ]
