# Generated by Django 3.1 on 2020-08-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='passage',
            field=models.TextField(default='passage', max_length=500),
            preserve_default=False,
        ),
    ]
