# Generated by Django 3.1 on 2020-08-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0002_multiplechoicequestion_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttaker',
            name='user',
        ),
        migrations.AddField(
            model_name='assessmenttaker',
            name='username',
            field=models.CharField(default='passage', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
