# Generated by Django 3.1 on 2020-09-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_choices', '0002_auto_20200901_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='multiplechoicequestion',
            options={},
        ),
    ]
