# Generated by Django 3.1 on 2020-11-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.TextField(unique=True)),
                ('grade', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.organisationalcbt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.TextField(unique=True)),
                ('grade', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.personalcbt')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
