# Generated by Django 3.1 on 2020-12-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionQuestionPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, max_length=500, null=True)),
                ('no_of_questions', models.IntegerField(blank=True, default=4, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.institutionassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstitutionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.TextField(unique=True)),
                ('score', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.institutionassessment')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.institutionquestionpassage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualQuestionPassage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField(blank=True, max_length=500, null=True)),
                ('no_of_questions', models.IntegerField(blank=True, default=4, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.individualassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndividualQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_asked', models.TextField(unique=True)),
                ('score', models.IntegerField(default=5)),
                ('no_of_choices', models.IntegerField(default=4)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.individualassessment')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.individualquestionpassage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
