# Generated by Django 3.1 on 2020-11-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualquestion',
            name='question_asked',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='institutionquestion',
            name='question_asked',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
