# Generated by Django 3.1 on 2020-11-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201127_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualquestion',
            old_name='grade',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='institutionquestion',
            old_name='grade',
            new_name='score',
        ),
    ]
